<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
$loadformurl = $this->helper('lr_callprice')->loadformurl();
?>
<?php
$_productCollection = $this->getLoadedProductCollection();
$_helper = $this->helper('catalog/output');
?>

<?php //echo $_productCollection->count(); ?>

<div class="page-title category-title">
    <h1><?php echo $this->getPageTitle() ?></h1>
</div>

<?php if( !empty($_productCollection) ) : ?>
    <?php if(!$_productCollection->count()): ?>
        <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
    <?php else: ?>
    <div class="category-products">
        <?php echo $this->getToolbarHtml() ?>

            <?php $_collectionSize = $_productCollection->count() ?>
            <?php $_columnCount = $this->getColumnCount(); ?>
            <div class="product-list-wrapper">
                <?php $i=0; foreach ($_productCollection as $_product): ?>
                    <?php if($i == 0 || $i % 2 == 0): $product_list_row_closed = false;?>
                        <div class="row">
                    <?php endif; ?>
                    <div class="col-xs-12 col-sm-6">
                        <div class="item_inner_wrapper">
                            <div class="row">
                                <div class="col-xs-12 col-sm-5">
                                    <div class="image-box">
                                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>" width="135" height="135" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-7">
                                    <div class="product-info-box">

                                        <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
                                        <div class="actions">
                                            <?php if($_product->isSaleable()): ?>
                                                <?php if($showCallForPriceButton==1):?>
                                                    <?php $buttonTitle = $this->helper("lr_callprice")->getButtonTitle(); ?>
                                                    <p><button type="button" title="<?php echo $buttonTitle ?>" class="button btn-cart" onClick="setLocation('<?php echo $_product->getProductUrl() ?>')"><span><span><?php echo $buttonTitle ?></span></span></button></p>
                                                <?php else:?>
                                                    <p><span class="fa fa-check green"></span> In Stock</p>
                                                <?php endif; ?>
                                            <?php else: ?>
                                                <p class="availability out-of-stock"><span class="fa fa-times red"></span> Out of Stock</p>
                                            <?php endif; ?>

                                        </div>

                                        <?php if($_product->getRatingSummary()): ?>
                                            <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                                        <?php endif; ?>
                                        <?php if($this->helper("lr_callprice")->showCallForPriceButton($_product)==1):?>
                                            <?php
                                            // Dont show Price
                                            $showCallForPriceButton = 1;
                                            ?>
                                        <?php else:?>
                                            <div class="price">
                                                <?php $showCallForPriceButton = 0; ?>
                                                <?php echo $this->getPriceHtml($_product, true) ?>
                                            </div>
                                        <?php endif; ?>

                                        <div class="more-info">
                                            <a href="<?php echo $_product->getProductUrl() ?>">
                                                <img src="<?php echo $this->getSkinUrl('images/more-info.png'); ?>" alt="Get more information">
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div> <!--.row-->
                        </div>
                    </div>
                    <?php if($i % 2 != 0): ?>
                        </div> <!--.row-->
                    <?php endif; $product_list_row_closed = true; ?>
                    <?php $i++; endforeach;  ?>
                <?php if(!$product_list_row_closed): ?>
            </div>
        <?php endif; ?>
            <?php echo $this->getToolbarHtml() ?>
        </div>
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
        </div>
    <?php endif; ?>

<?php else: ?>  
        <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php endif; ?>
